name: befi_ibeu
description: "Official application for BEFI - IBEU"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.1+4

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.2.6
  google_nav_bar: ^5.0.6
  internet_file: ^1.2.0
  pdfx: ^2.6.0
  path_provider: ^2.1.3
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/